@startuml

interface ICancelable {
  +{abstract} bool Do()
  +{abstract} void Cancel()
}

abstract CancelableProcessBase {
  +bool Do()
  +void Cancel()
  #{abstract} bool DoImpl()
  #bool ShouldCancel() const
}

class ConcreteProcess {
  -bool DoImpl()
}

ICancelable <|.u. CancelableProcessBase
CancelableProcessBase <|-u- ConcreteProcess

class WorkerThreadManager {
	+void push_back(std::shared_ptr<ICancelable>);
	+bool get_result() const;
}

class CProgressDialog {
  +CProgressDialog(CWnd*, std::shared_ptr<ICancelable>)
  #BOOL OnInitDialog()
  +void OnBnClickedCancel()
}

class MainDialog {
  +void OnBnClickedBtnProcess()
}

CProgressDialog -d-> WorkerThreadManager : m_task_manager

WorkerThreadManager -l-> ICancelable : m_process

MainDialog .l. ConcreteProcess
MainDialog .d. CProgressDialog

@enduml
