@startuml

Actor ユーザ as user
participant MainDialog
participant CProgressDialog
participant CProgressCtrl
participant WorkerThreadManager
participant ConcreteProcess

user -> MainDialog : 処理開始ボタン押下
activate MainDialog

  MainDialog -> MainDialog : OnBnClickedBtnProcess
  activate MainDialog

    create ConcreteProcess
    MainDialog-> ConcreteProcess : <<create>>

    activate ConcreteProcess

      MainDialog <-- ConcreteProcess

      create CProgressDialog
      MainDialog -> CProgressDialog : <<create>>
      activate CProgressDialog

        create CProgressCtrl
        CProgressDialog -> CProgressCtrl : <<create>>
        activate CProgressCtrl
          CProgressDialog <-- CProgressCtrl

          create WorkerThreadManager
          CProgressDialog -> WorkerThreadManager : <<create>>
          activate WorkerThreadManager
            CProgressDialog <-- WorkerThreadManager

            MainDialog <-- CProgressDialog

            MainDialog-> CProgressDialog : DoModal()

            CProgressDialog -> CProgressDialog : OnInitDialog
            activate CProgressDialog

              CProgressDialog -> CProgressCtrl : SetMarquee(TRUE)
              CProgressDialog -> WorkerThreadManager : push_back
              CProgressDialog <-- WorkerThreadManager

par
              WorkerThreadManager -> ConcreteProcess : Do()

              ConcreteProcess -> ConcreteProcess : DoImpl()
              activate ConcreteProcess

                ConcreteProcess -> ConcreteProcess : ShouldCancel()
                activate ConcreteProcess
                deactivate ConcreteProcess

                WorkerThreadManager <-- ConcreteProcess : 終了ステータス

              deactivate ConcreteProcess

              CProgressDialog <- WorkerThreadManager : ActionWhenProcessExecutes()
              activate CProgressDialog
                CProgressDialog -> CProgressCtrl : SetMarquee(FALSE)
              deactivate CProgressDialog

end
              CProgressDialog <- WorkerThreadManager : ActionWhenThreadEnds()
              activate CProgressDialog

                CProgressDialog -> CProgressDialog : OnCloseProgressDialog
                activate CProgressDialog
                  CProgressDialog -> WorkerThreadManager : get_result()
                  CProgressDialog <-- WorkerThreadManager : 終了ステータス

                  CProgressDialog -> CProgressDialog : EndDialog
                  activate CProgressDialog
                    MainDialog <-- CProgressDialog
                  deactivate CProgressDialog
                deactivate CProgressDialog
              deactivate CProgressCtrl
            deactivate CProgressDialog
          deactivate CProgressDialog
        deactivate CProgressDialog
      deactivate WorkerThreadManager
    deactivate ConcreteProcess
  deactivate MainDialog
deactivate MainDialog

@enduml
